blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('categories', views.categories, name='categories'),
    path('category/<str:category_name>/', views.category, name='category'),
    path('create_category', views.create_category, name='create_category'),
    path('latest_article', views.latest_article, name='latest_article'),
    path('create_article/', views.create_article, name='create_article'),
    path('read/<str:article_title>/',
         views.read_article, name='read_article'),
    path('update/<str:article_title>/',
         views.update_article, name='update_article'),
    path('delete/<str:article_title>/',
         views.delete_article, name='delete_article'),
    path('articles/', views.home, name='articles'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

localcode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    path('logout', views.logout_users, name='logout'),

]

blog/models.py
from django.db import models
from tinymce import HTMLField
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'categories'

    def __str__(self):
        return self.name


class Article(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    subtitle = models.CharField(max_length=200)
    text = HTMLField()
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_created']
        get_latest_by = ['-date_created']

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Article, Category


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['category', 'title', 'subtitle', 'text', ]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', ]

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from el_pagination.decorators import page_template
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings

from .models import Article, Category
from .forms import ArticleForm, CategoryForm


def username_check(user):
    return user.username == settings.USER_ADMIN


@page_template('blog/entry_list_page.html')
def home(request,
         template='blog/home.html',
         extra_context=None):
    context = {
        'articles': Article.objects.all(),
    }
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@user_passes_test(username_check)
@login_required(login_url='users:login')
def create_article(request):
    if request.method != 'POST':
        form = ArticleForm()
    else:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.owner = request.user
            new_article.save()
            return HttpResponseRedirect(reverse('blog:latest_article'))
    context = {'form': form}
    return render(request, 'blog/create_article.html', context)


def read_article(request, article_title):
    article = Article.objects.get(title=article_title)
    context = {'article': article}
    return render(request, 'blog/read_article.html', context)


@user_passes_test(username_check)
@login_required(login_url='users:login')
def update_article(request, article_title):
    article = Article.objects.get(title=article_title)
    category_ = article.category
    if article.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = ArticleForm(instance=article)
    else:
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('blog:category', args=[category_.name]))
    context = {'article': article, 'form': form}
    return render(request, 'blog/update_article.html', context)


@login_required(login_url='users:login')
def latest_article(request):
    article = Article.objects.order_by('-date_created')[0]
    context = {'article': article}
    return render(request, 'blog/read_article.html', context)


@user_passes_test(username_check)
@login_required(login_url='users:login')
def delete_article(request, article_title):
    article = get_object_or_404(Article, title=article_title)
    category = article.category
    if article.owner != request.user:
        raise Http404
    if request.method == 'POST':
        article.delete()
        return HttpResponseRedirect(reverse('blog:category', args=[category.name]))


@user_passes_test(username_check)
@login_required(login_url='users:login')
def create_category(request):
    if request.method != 'POST':
        form = CategoryForm()
    else:
        form = CategoryForm(request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('blog:categories'))
    context = {'form': form}
    return render(request, 'blog/create_category.html', context)


@page_template('blog/entry_list_page.html')
@login_required(login_url='users:login')
def category(request, category_name, template='blog/category.html', extra_context=None):
    category_ = Category.objects.get(name=category_name)
    articles = category_.article_set.all()
    context = {'category': category, 'articles': articles}
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@login_required(login_url='users:login')
def categories(request):
    list_categories = Category.objects.all()
    context = {'categories': list_categories}
    return render(request, 'blog/categories.html', context)


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">About</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
           <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <p>Hi guys all right?</p>

                               <p>I'm just like you dig write code but at times I forget how to do something  Dory.jpg</p>

                               <p>So I wrote this blog.If you want to talk, then somewhere here were my <a href = "{% url 'blog:contact' %}">contacts.</a></p>

                               <p>Abysinnia!</p>
                    </div>
                </div>
            </div>
        </div>
                <hr>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">


<head>
  {% load bootstrap3 %}
  {% load staticfiles %}
  {% load socialaccount %}
  {% load social_share %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="python, django, web_development">
    <meta name="author" content="sixth_fox">

    <title>LocalCode</title>

    <!--Tinymce Text-Editor (Must be in Head Tag) -->
    <script src='https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=a6q0u1v491tv24ahs8e4u9hpqonzd1bcppbhed8humirbt9z'></script>
    <script src="{% static 'blog/js/tinymce/main_tinymce.js' %}"></script>

    <!-- favicon -->
    <link href="{% static 'blog/img/favicon.ico' %}" type="image/x-icon" rel="shortcut icon">

    <!-- Prism -->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/js/tinymce/plugins/codesample/css/prism.css' %}">
    <script src="{% static 'blog/js/tinymce/plugins/codesample/js/prism.js' %}"></script>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'blog/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom Select Form -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="logo" href="{% url 'blog:home' %}">
                <img src="{% static 'blog/img/logo.png'%}" class="img-responsive" alt="LocalCode"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% if user.is_superuser %}
                <ul class="nav navbar-nav navbar-left">
                    <li role="presentation">
                        <a href="{% url 'blog:create_article' %}">New Article</a>
                    </li>
                </ul>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    <li role="presentation">
                        <a href="{% url 'blog:home' %}">Home</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'blog:about' %}">About</a>
                    </li>
                    <li role="presentation">
                        <a href="{% url 'blog:contact' %}">Contact</a>
                    </li>
                    <li role="presentation">
                        {% if user.is_authenticated %}
                          <a href="{% url 'users:logout' %}">{{ user.username }}</a>
                        {% else %}
                          <a href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

{% block header %}{% endblock header %}
{% block content %}{% endblock content %}

<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            {% if user.is_authenticated %}
                           <a href="{% provider_login_url "twitter" process="connect" method="js_sdk"%}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            <a href="{% provider_login_url "google" process="connect" method="js_sdk"%}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-google fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            <a href="{% provider_login_url "github" process="connect" method="js_sdk" %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            {% else %}
                            <a href="{% provider_login_url "twitter" process="login" method="js_sdk" %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            <a href="{% provider_login_url "google" process="login" method="js_sdk" %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-google fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            <a href="{% provider_login_url "github" process="login" method="js_sdk" %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                            {% endif %}

                        </li>
                    </ul>
                </div>
            </div>
            <p class="copyright text-muted">Copyright &copy; 6th_fox 2k18</p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blog/templates/blog/categories.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load el_pagination_tags %}
{% load social_share %}
{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">One more things</span>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
  {% for category in categories %}
    <a href="{% url 'blog:category' category.name %}">{{category.name}}</a>
  {% endfor %}
{% endblock content %}

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load el_pagination_tags %}
{% load social_share %}
{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">One more things</span>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
        <!-- Main Content -->
<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
{% include page_template %}
   {% block js %}
    {{ block.super }}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>
    <script>$.endlessPaginate({paginateOnScroll: true});</script>
    {% endblock %}
</div>
{% endblock content %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">My Contacts</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Round the clock, without breaks and days off</p>
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls ">
                            <label>Email</label>
                            <p class="form-control-static">i.pyatigorets@gmail.com</p>
                            <a href="https://plus.google.com/u/0/114770436914598989729">G+</a>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Twitter</label>
                            <p class="form-control-static">@sixth_fox</p>
                            <a href="https://twitter.com/sixth_fox">Twitter</a>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>GitHub</label>
                            <p class="form-control-static">i.pyatigorets</p>
                            <a href="https://github.com/sixth-fox">GitHub</a>
                        </div>
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </div>

    <hr>
{% endblock content %}

blog/templates/blog/create_article.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">Learned something new? Tell me!</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <form action="{% url 'blog:create_article' %}" id="contactForm" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}

                    {% bootstrap_form form %}

                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>
{% endblock content %}

blog/templates/blog/entry_list_page.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load el_pagination_tags %}
{% load social_share %}

{% block content %}
        <!-- Main Content -->
    <!-- Prism -->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/js/tinymce/plugins/codesample/css/prism.css' %}">
    <script src="{% static 'blog/js/tinymce/plugins/codesample/js/prism.js' %}"></script>

                {% paginate articles %}
                {% for article in articles %}
                <div class="post-preview">
                    <a href="{% url 'blog:read_article' article.title %}">
                        <h3 class="post-title">
                            {{ article.title }}
                        </h3>
                        <h3 class="post-subtitle">
                            {{ article.subtitle }}
                        </h3>
                        </a>
                        <p class="post-meta">Posted by {{ article.owner }}
                            {{ article.date_created|date:'M d, Y H:i' }}</p>
                        <p>
                            <div class="post-meta">{% bootstrap_icon "tag" %}<a
                                    href="{% url 'blog:category' article.category %}">{{ article.category }}</a></div>
                        </p>
                        {{ article.text|safe }}
                    </a>
                    <p class="post-meta">{% post_to_twitter "New Article: {{object.title}}. Check it out!" object_or_url "Post to Twitter" %}
                    {% post_to_linkedin object.title object_or_url "Post to LinkedIn" %}</p>

                </div>
                <hr>
                {% endfor %}
                {% show_more %}

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block header %}
{% load social_share %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">One more things</span>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
        <!-- Main Content -->
<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
{% include page_template %}
   {% block js %}
    {{ block.super }}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>
    <script>$.endlessPaginate({
    paginateOnScroll: true,
    paginateOnScrollMargin: 200});</script>
    {% endblock %}
</div>
{% endblock content %}

blog/templates/blog/read_article.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">One more things</span>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-preview">
                        <h1>{{ article.title }}</h1>
                        <h3 class="subheading">{{ article.subtitle }}</h3>
                        <p class="post-meta">Posted by <a href="{{article.owner.id}}">{{article.owner}}</a> {{ article.date_created|date:'M d, Y H:i' }}</p>
                        <small><p class="post-meta">{% bootstrap_icon "tag" %}<a
                                href="{% url 'blog:category' article.category %}">{{ article.category }}</a></p></small>
                            {% if request.user.is_superuser %}
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Tools
                                <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <li>
                                        <form action="{% url 'blog:delete_article' article.title %}" method="post">
                                           {% csrf_token %}
                                           <button type="submit" class="btn btn-default">Remove
                                              {% bootstrap_icon "remove" %}
                                            </button>
                                        </form>
                                    </li>
                                    <li><a href="{% url 'blog:update_article' article.title %}">
                                            <button type="submit" class="btn btn-default">Edit
                                               {% bootstrap_icon "edit" %}
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            {% endif %}
                        <hr>
                        {{ article.text|safe }}
                    </div>
                    <hr>
                </div>
            </div>
    </div>
{% endblock content %}

blog/templates/blog/update_article.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block header %}
        <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{LocalCode}</h1>
                        <hr class="small">
                        <span class="subheading">Learned something new? Tell me!</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <form action="{% url 'blog:update_article' article.title %}" id="contactForm" method="post"
                      enctype="multipart/form-data" novalidate>
                    {% csrf_token %}

                    {% bootstrap_form form %}

                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>
{% endblock content %}